# PROD config

version: '2'
services:
  app:
    extends:
      file: docker-compose-services.yml
      service: app
    links:
      - postgres
    environment:
      - NODE_ENV=production
    command: node server.js
  postgres:
    extends:
      file: docker-compose-services.yml
      service: postgres